### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by WxZy530** [why2011btv/JointConstrainedLearning#1]
你好，在尝试使用Joint联合训练（with finetune）时，会报出以下错误的情况

Traceback (most recent call last):
  File "main_aug.py", line 294, in <module>
    joint_exp.train()
  File "/home/wangxiao/JointConstrainedLearning-master/exp.py", line 107, in train
    alpha_logits, beta_logits, gamma_logits, loss = self.model(x_sent, y_sent, z_sent, x_position, y_position, z_position, xy, yz, xz, flag, loss_out = True)
  File "/home/wangxiao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangxiao/JointConstrainedLearning-master/model_aug.py", line 140, in forward
    loss += self.HiEve_anno_loss(alpha_logits[i][0:4], xy[i]) + self.HiEve_anno_loss(beta_logits[i][0:4], yz[i]) + self.HiEve_anno_loss(gamma_logits[i][0:4], xz[i])
  File "/home/wangxiao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangxiao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/wangxiao/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/wangxiao/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1317, in log_softmax
    ret = input.log_softmax(dim)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

似乎说明的是alpha_logits[i][0:4]的第一个参数大于0，alpha_logits[0]=tensor([[ 1.2342, -1.2112, -2.3994, -1.5573,  4.4717,  0.0225, -3.6911, -0.6784],实际也确实如此，对于代码并没有做额外的修改，想请问您是否碰到过类似的问题，或者有什么好的建议

**Comment by Peng-KG** [comment]
你好，这个问题你解决了吗

**Comment by WxZy530** [comment]
还是没有解决。

**Comment by why2011btv** [comment]
Really appreciate your raising this issue! I have fixed them now. Thanks
